pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                dir('travelmaker_backend'){
                    script{
                        sh 'pwd'
                        sh 'ls'
                        sh 'chmod +x gradlew'
                        sh './gradlew clean build'
                        sh 'chmod +x ./docker_install.sh'
                        sh './docker_install.sh'
                    }
                }
            }
        }
        stage('Deploy'){
            steps{
                script{
                    sh 'sudo systemctl start docker'
                    sh 'sudo systemctl enable docker'
                    sh 'docker build -t jenkins .'
                    sh 'docker rm -f jenkins'
                    sh 'docker run -d --name jenkins -p 9090:8080 jenkins'
                }
            }
        }
    }

    post {
        success {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'good',
                message: "빌드 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                endpoint: 'https://meeting.ssafy.com/hooks/jpyak6ugbtygzdbaqjkhy8bmrw',
                channel: 'D202-Jenkins'
                )
            }
        }
        failure {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'danger',
                message: "빌드 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                endpoint: 'https://meeting.ssafy.com/hooks/jpyak6ugbtygzdbaqjkhy8bmrw',
                channel: 'D202-Jenkins'
                )
            }
        }
    }
}